## Tahap 1 - Gathering Data

Pada tahap ini dilakukan proses pengumpulan data dengan membaca dataset lowongan pekerjaan dari file `job-vacancy-dataset.csv`.

Dataset kemudian dimuat menggunakan library `pandas` untuk mempermudah proses analisis lebih lanjut.

Output dari tahap ini adalah:
- Dataset berhasil dimuat ke dalam DataFrame
- Mengetahui jumlah baris data (record)
- Mengetahui jumlah kolom (fitur)

Tahap ini merupakan langkah awal dalam data pipeline sebelum dilakukan eksplorasi dan pembersihan data.

In [32]:
import pandas as pd
import re
# GATHERING DATA print
print("TAHAP 1 - GATHERING DATA")
print("Membaca dataset job vacancy...")

df = pd.read_csv( "job-vacancy-dataset.csv", low_memory=False )

print("Dataset berhasil dibaca.")
print(f"Jumlah data : {len(df)}")
print(f"Jumlah kolom : {len(df.columns)}")

TAHAP 1 - GATHERING DATA
Membaca dataset job vacancy...
Dataset berhasil dibaca.
Jumlah data : 63870
Jumlah kolom : 18

## Tahap 2 - Assessing Data

Tahap ini bertujuan untuk mengevaluasi kondisi awal dataset sebelum dilakukan proses cleaning.

Evaluasi dilakukan melalui beberapa aspek:

### 1. Informasi Dataset
Menampilkan struktur dataset seperti:
- Nama kolom
- Tipe data setiap kolom
- Jumlah missing value

### 2. Missing Value Analysis
Mengidentifikasi jumlah data kosong (NaN) pada setiap kolom untuk mengetahui kualitas kelengkapan data.

### 3. Data Duplikat
Mengecek apakah terdapat data yang terduplikasi dalam dataset.

### 4. Sample Data
Menampilkan 5 data teratas untuk memahami bentuk dan isi dataset.

### 5. Noise Detection (Data Kotor)
Dilakukan analisis kualitas data untuk mendeteksi:
- Simbol khusus (., #, dll)
- Huruf kapital yang tidak konsisten
- Encoding error (misalnya â€œ, â€“)
- Spasi berlebih

Tahap ini penting untuk mengetahui apakah dataset masih mengandung noise yang perlu dibersihkan sebelum digunakan pada analisis atau model.

In [29]:
# ASSESSING DATA
print("TAHAP 2 - ASSESSING DATA")

# 1. INFORMASI DATASET
print("\n1. INFORMASI DATASET")
info_df = pd.DataFrame({ "Kolom": df.columns, "Tipe Data": df.dtypes.values, "Missing Values": df.isnull().sum().values })
display(info_df)

# 2. MISSING VALUES
print("\n2. MISSING VALUES")

missing_df = pd.DataFrame({
    "Kolom": df.columns,
    "Jumlah Missing": df.isnull().sum().values
})

display(missing_df)

# 3. DATA DUPLIKAT
print("\n3. DATA DUPLIKAT")

duplicate_df = pd.DataFrame({
    "Keterangan": ["Jumlah Data Duplikat"],
    "Total": [df.duplicated().sum()]
})

display(duplicate_df)

# 4. CONTOH DATA
print("\n4. CONTOH DATA")
display(df.head())

print("CEK KUALITAS DATA (NOISE DETECTION)")

#5.FUNCTION PATTERN
def count_pattern(column, pattern):
    return df[column].astype(str).str.contains(pattern, na=False).sum()

# SIMBOL KHUSUS
symbol_pattern = r'[^\w\s]'
# HURUF KAPITAL
uppercase_pattern = r'[A-Z]'
# ENCODING RUSAK
encoding_pattern = r'â|�'
# SPASI BERLEBIH
space_pattern = r'\s{2,}'
# HITUNG SEMUA NOISE
quality_check = pd.DataFrame({
    "Jenis Noise": [
        "Simbol Khusus",
        "Huruf Kapital",
        "Encoding Rusak",
        "Spasi Berlebih"
    ],
    "Title": [
        count_pattern("title", symbol_pattern),
        count_pattern("title", uppercase_pattern),
        count_pattern("title", encoding_pattern),
        count_pattern("title", space_pattern)
    ],
    "Requirement": [
        count_pattern("requirement", symbol_pattern),
        count_pattern("requirement", uppercase_pattern),
        count_pattern("requirement", encoding_pattern),
        count_pattern("requirement", space_pattern)
    ],
    "Description": [
        count_pattern("description", symbol_pattern),
        count_pattern("description", uppercase_pattern),
        count_pattern("description", encoding_pattern),
        count_pattern("description", space_pattern)
    ]
})

display(quality_check)

TAHAP 2 - ASSESSING DATA

1. INFORMASI DATASET

                  Kolom Tipe Data  Missing Values
0                  logo    object            5432
1                 title    object               0
2               company    object               0
3              location    object            4466
4      min_company_size     int64               0
5      max_company_size     int64               0
6          type_of_work    object           41247
7           requirement    object            5466
8             job_level    object           50492
9           description    object           13063
10  min_work_experience     int64               0
11  max_work_experience     int64               0
12        qualification    object           17836
13             currency    object           52434
14           min_salary    object               0
15           max_salary    object               0
16                 time    object               0
17                 link    object               0

2. MISSING VALUES

                  Kolom  Jumlah Missing
0                  logo            5432
1                 title               0
2               company               0
3              location            4466
4      min_company_size               0
5      max_company_size               0
6          type_of_work           41247
7           requirement            5466
8             job_level           50492
9           description           13063
10  min_work_experience               0
11  max_work_experience               0
12        qualification           17836
13             currency           52434
14           min_salary               0
15           max_salary               0
16                 time               0
17                 link               0

3. DATA DUPLIKAT

             Keterangan  Total
0  Jumlah Data Duplikat      7

4. CONTOH DATA

,logo,title,company,location,min_company_size,max_company_size,type_of_work,requirement,job_level,description,min_work_experience,max_work_experience,qualification,currency,min_salary,max_salary,time,link
0,https://images.glints.com/unsafe/glints-dashbo...,Business Development Officer,Pt Kebun Bumi Lestari,Semarang,0,0,Penuh Waktu,Business Development / Sales | Skills B2B Mark...,NaN,Deskripsi pekerjaan Business Development Offic...,0,1,NaN,NaN,0,0,01/01/1970 00:00:00,https://glints.com/id/opportunities/jobs/busin...
1,https://images.glints.com/unsafe/glints-dashbo...,Account Manager,PT Health Today Indonesia,Cilandak,0,0,Penuh Waktu,Business Development / Sales | Skills Customer...,NaN,Deskripsi pekerjaan Account Manager PT Health ...,1,3,NaN,NaN,0,0,01/01/1970 00:00:00,https://glints.com/id/opportunities/jobs/accou...
2,https://images.glints.com/unsafe/glints-dashbo...,Staff Marketing Executive,PT. Graha Mutu Persada,Mojokerto,0,0,Penuh Waktu,Business Development / Sales | Skills Marketin...,NaN,Deskripsi pekerjaan Staff Marketing Executive ...,1,3,NaN,NaN,0,0,01/01/1970 00:00:00,https://glints.com/id/opportunities/jobs/staff...
3,https://images.glints.com/unsafe/glints-dashbo...,Sales Executive Semarang,Iron Bird Logistic,Semarang,0,0,Penuh Waktu,Business Development / Sales | Skills Komunika...,NaN,Deskripsi pekerjaan Sales Executive Semarang I...,1,3,NaN,NaN,0,0,01/01/1970 00:00:00,https://glints.com/id/opportunities/jobs/sales...
4,https://images.glints.com/unsafe/glints-dashbo...,Performance Marketing Specialist,ErudiFi,Jakarta,0,0,Penuh Waktu,Marketing | Skills Performance Marketing A/B T...,NaN,Deskripsi pekerjaan Performance Marketing Spec...,1,3,NaN,NaN,0,0,01/01/1970 00:00:00,https://glints.com/id/opportunities/jobs/perfo...

CEK KUALITAS DATA (NOISE DETECTION)

      Jenis Noise  Title  Requirement  Description
0   Simbol Khusus  18242        57179        43793
1   Huruf Kapital  63785        58404        50797
2  Encoding Rusak      0            0            1
3  Spasi Berlebih    142        49397        34122

## Tahap 3 - Cleaning Data

Tahap ini merupakan proses pembersihan data untuk meningkatkan kualitas dataset agar siap digunakan dalam analisis.

### 1. Text Cleaning
Dilakukan pembersihan pada kolom teks (`title`, `requirement`, `description`) dengan langkah:
- Mengubah teks menjadi lowercase
- Menghapus karakter non-ASCII
- Menghapus URL
- Menghapus simbol dan tanda baca
- Merapikan spasi berlebih

### 2. Filtering Data
Dataset difilter berdasarkan kata kunci pekerjaan tertentu seperti:
- Cyber Security
- Software Engineer
- Data Analyst
- Accounting
- Electrical Engineer

Tujuan filtering ini adalah untuk fokus pada domain pekerjaan yang relevan dengan project capstone.

### 3. Cleaning Data Numerik
Kolom numerik seperti:
- salary
- company size
- work experience

dibersihkan dengan cara:
- Mengubah ke format numerik
- Mengisi nilai kosong dengan 0

### 4. Handling Missing Value
Seluruh missing value pada kolom non-numerik diganti dengan nilai `"None"` agar tidak ada data kosong dalam dataset.

### 5. Cleaning Time Column
Kolom waktu dibersihkan dari karakter tidak valid dan nilai error seperti `###`.

In [30]:
# CLEANING DATA
print("TAHAP 3 - CLEANING DATA")

# 1. FUNGSI CLEAN TEXT
print("Membuat fungsi clean_text...")
def clean_text(text):
    if pd.isna(text) or not isinstance(text, str) or str(text).strip() == "":
        return "None"

    # Lowercase
    text = text.lower()

    # Hapus karakter non-ascii
    text = text.encode('ascii', 'ignore').decode('ascii')

    # Hapus URL
    text = re.sub(r'https?://\s*\S+|www\.\S+', '', text)

    # Hapus simbol
    text = re.sub(r'[^\w\s]', ' ', text)

    # Rapihkan spasi
    text = re.sub(r'\s+', ' ', text).strip()
    return text if text != "" else "None"
print("Fungsi clean_text berhasil dibuat.\n")

# 2. FILTER PEKERJAAN TARGET
print("Filtering pekerjaan target...")
keywords_pattern = (
    r'cyber\s*security|information\s*security|network\s*security|penetration\s*tester|keamanan\s*informasi|'
    r'staff\s*akuntansi|accounting\s*staff|accounting\s*officer|teknisi\s*akuntansi|junior\s*accountant|'
    r'\bprogrammer\b|software\s*engineer|web\s*developer|backend\s*developer|frontend\s*developer|fullstack\s*developer|'
    r'data\s*analyst|data\s*analytics|junior\s*data\s*analyst|'
    r'insinyur\s*elektro|electrical\s*engineer|teknisi\s*elektro|teknisi\s*listrik'
)

df['title'] = df['title'].astype(str)
df = df[
    df['title']
    .str.lower()
    .str.contains(keywords_pattern, na=False, regex=True)
].copy()
print("Filtering pekerjaan berhasil.")
print(f"Jumlah data setelah filtering : {len(df)}\n")

# 3. CLEANING KOLOM TEKS
print("Membersihkan kolom teks...")
text_columns = ['title', 'requirement', 'description']
for col in text_columns:
    if col in df.columns:
        df[col] = df[col].apply(clean_text)
print("Kolom teks berhasil dibersihkan.\n")

# 4. CLEANING DATA NUMERIK
print("Membersihkan data numerik...")
numeric_columns = [
    'min_company_size',
    'max_company_size',
    'min_work_experience',
    'max_work_experience',
    'min_salary',
    'max_salary'
]

for col in numeric_columns:
    if col in df.columns:
        df[col] = (
            pd.to_numeric(df[col], errors='coerce')
            .fillna(0)
            .astype(int)
        )
print("Data numerik berhasil dibersihkan.\n")

# 5. CLEANING MISSING VALUES
print("Membersihkan missing values...")
for col in df.columns:
    if col not in numeric_columns:
        df[col] = df[col].fillna('None')
        df[col] = df[col].astype(str)
        df[col] = df[col].replace(
            r'^\s*$',
            'None',
            regex=True
        )
        df[col] = df[col].replace(
            ['nan', 'NaN'],
            'None'
        )

print("Missing values berhasil dibersihkan.\n")

# 6. CLEANING KOLOM WAKTU
print("Membersihkan kolom waktu...")
if 'time' in df.columns:
    df['time'] = df['time'].astype(str)
    df['time'] = df['time'].str.replace(
        r'#+',
        'None',
        regex=True
    )

print("Kolom waktu berhasil dibersihkan.\n")

TAHAP 3 - CLEANING DATA
Membuat fungsi clean_text...
Fungsi clean_text berhasil dibuat.

Filtering pekerjaan target...
Filtering pekerjaan berhasil.
Jumlah data setelah filtering : 2516

Membersihkan kolom teks...
Kolom teks berhasil dibersihkan.

Membersihkan data numerik...
Data numerik berhasil dibersihkan.

Membersihkan missing values...
Missing values berhasil dibersihkan.

Membersihkan kolom waktu...
Kolom waktu berhasil dibersihkan.

### Save Dataset
Hasil akhir cleaning disimpan ke file baru `cleaned_job_5.csv` untuk digunakan pada tahap analisis atau modeling selanjutnya.

In [26]:
# MENYIMPAN HASIL AKHIR
print("Menyimpan hasil akhir...")

output_file = "cleaned_job_5.csv"

df.to_csv(output_file, index=False)

print("DATASET BERHASIL DIBERSIHKAN")
print(f"Output tersimpan di: {output_file}")

Menyimpan hasil akhir...
DATASET BERHASIL DIBERSIHKAN
Output tersimpan di: cleaned_job_5.csv